version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5
    tty: true
    stdin_open: true

  ui:
    build: ./ui
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
