name: Build and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask joblib scikit-learn pandas streamlit requests numpy

    - name: Check Python files syntax
      run: |
        python -m py_compile api/app.py
        python -m py_compile training/main.py
        python -m py_compile ui/streamlit_app.py
